# Generated by Django 2.1.3 on 2019-02-25 07:01

import content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0025_auto_20180429_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_file', models.FileField(upload_to=content_management.models.MetadataSheet.set_original_name, verbose_name='File')),
                ('updated_time', models.DateField(help_text='Date when the content was last updated', verbose_name='Content updated on')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
