# Generated by Django 2.1.3 on 2019-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0026_metadatasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatasheet',
            name='updated_time',
            field=models.DateTimeField(help_text='Date when the content was last updated', verbose_name='Content updated on'),
        ),
    ]
