# Generated by Django 2.1.3 on 2019-02-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0029_metadatasheet_original_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatasheet',
            name='original_file_name',
        ),
    ]
