# Generated by Django 2.1.3 on 2019-03-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0030_remove_metadatasheet_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatasheet',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
