# Generated by Django 2.1.3 on 2019-12-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0033_auto_20191220_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='active',
        ),
    ]
