# Generated by Django 2.1.3 on 2020-01-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0035_content_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='audience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='collections_need_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.Collection'),
        ),
        migrations.AddField(
            model_name='directory',
            name='collections',
            field=models.ManyToManyField(to='content_management.Collection'),
        ),
    ]
