# Generated by Django 2.1.3 on 2020-01-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0036_auto_20200124_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='collection',
        ),
        migrations.AddField(
            model_name='content',
            name='collection',
            field=models.ManyToManyField(to='content_management.Collection'),
        ),
    ]
