# Generated by Django 2.1.3 on 2020-01-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0037_auto_20200124_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='collection',
            new_name='collections',
        ),
    ]
