# Generated by Django 2.1.3 on 2020-02-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0039_auto_20200212_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='published_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='audience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.Audience'),
        ),
    ]
