# Generated by Django 2.1.3 on 2020-02-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0040_auto_20200212_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='content',
            name='resourcetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.ResourceType'),
        ),
    ]
