# Generated by Django 2.1.3 on 2020-02-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0041_auto_20200212_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='audiences_need_all',
            field=models.BooleanField(default=False),
        ),
    ]
