# Generated by Django 2.1.3 on 2020-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0042_directory_audiences_need_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='resourcetypes_need_all',
            field=models.BooleanField(default=False),
        ),
    ]
