# Generated by Django 2.1.3 on 2020-02-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0043_directory_resourcetypes_need_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='audiences',
            field=models.ManyToManyField(to='content_management.Audience'),
        ),
        migrations.AddField(
            model_name='directory',
            name='resourcetypes',
            field=models.ManyToManyField(to='content_management.ResourceType'),
        ),
    ]
