# Generated by Django 2.1.3 on 2020-02-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0044_auto_20200227_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='updated_time',
            field=models.DateField(help_text='Date when the content was last updated', null=True, verbose_name='Content updated on'),
        ),
    ]
