# Generated by Django 2.1.3 on 2020-02-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0045_auto_20200228_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='collections',
        ),
        migrations.AddField(
            model_name='content',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.Collection'),
        ),
    ]
